const usersData = [
  {
    id: 0,
    name: "John Doe",
    registered: "2018-01-01",
    role: "Guest",
    status: "수리중",
  },
  {
    id: 1,
    name: "Samppa Nori",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 2,
    name: "Estavan Lykos",
    registered: "2018/02/01",
    role: "Staff",
    status: "고장",
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Derick Maximinus",
    registered: "2018/03/01",
    role: "Member",
    status: "수리중",
  },
  {
    id: 5,
    name: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 6,
    name: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 7,
    name: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "고장",
  },
  {
    id: 8,
    name: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 9,
    name: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 10,
    name: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "고장",
  },
  {
    id: 11,
    name: "Derick Maximinus",
    registered: "2018/03/01",
    role: "Member",
    status: "수리중",
  },
  {
    id: 12,
    name: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 13,
    name: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
  },
  {
    id: 14,
    name: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "고장",
  },
  {
    id: 15,
    name: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Active",
  },
  {
    id: 16,
    name: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Member",
    status: "사용중",
  },
  {
    id: 17,
    name: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "고장",
  },
];

export default usersData;
