const stationData = {
  stationList: [
    {
      name: "A관",
      availableDeviceCount: 8,
      totalDeviceCount: 120,
      floors: [
        {
          floor: "B1",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 6,
              checking_count: 4,
              usable_count: 7,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 4,
              checking_count: 2,
              usable_count: 7,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 5,
              checking_count: 2,
              usable_count: 7,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 7,
              usable_count: 8,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 4,
              usable_count: 27,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 7,
              checking_count: 1,
              usable_count: 54,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 7,
              checking_count: 1,
              usable_count: 54,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B2",
          areaList: [
            {
              area_name: "A2-1",
              breakdown_count: 2,
              checking_count: 7,
              usable_count: 61,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 5,
              checking_count: 2,
              usable_count: 27,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 1,
              checking_count: 0,
              usable_count: 16,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 6,
              checking_count: 2,
              usable_count: 45,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 6,
              checking_count: 2,
              usable_count: 67,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 1,
              usable_count: 34,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 1,
              usable_count: 34,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 1,
              usable_count: 34,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B3",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 1,
              checking_count: 1,
              usable_count: 67,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 4,
              usable_count: 1,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 7,
              usable_count: 57,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 3,
              checking_count: 4,
              usable_count: 26,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 1,
              checking_count: 1,
              usable_count: 72,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 1,
              checking_count: 7,
              usable_count: 25,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B4",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 5,
              checking_count: 7,
              usable_count: 27,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 7,
              usable_count: 14,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 11,
              checking_count: 3,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 1,
              checking_count: 6,
              usable_count: 70,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 60,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 5,
              checking_count: 4,
              usable_count: 70,
              total_count: 80,
            },
          ],
        },
      ],
    },
    {
      name: "B관",
      availableDeviceCount: 8,
      totalDeviceCount: 120,
      floors: [
        {
          floor: "B1",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 6,
              checking_count: 8,
              usable_count: 9,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 6,
              usable_count: 54,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 5,
              usable_count: 69,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 3,
              checking_count: 7,
              usable_count: 39,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 9,
              usable_count: 39,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 2,
              checking_count: 3,
              usable_count: 70,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B2",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B3",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B4",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
      ],
    },
    {
      name: "C관",
      availableDeviceCount: 8,
      totalDeviceCount: 120,
      floors: [
        {
          floor: "B1",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B2",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B3",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
        {
          floor: "B4",
          areaList: [
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
            {
              area_name: "A-1",
              breakdown_count: 10,
              checking_count: 7,
              usable_count: 6,
              total_count: 80,
            },
          ],
        },
      ],
    },
  ],
};

export default stationData;
